# Generated by Django 3.2.18 on 2023-04-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=80)),
                ('debit_credit', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
            ],
        ),
    ]
